#!/bin/bash

set -e
set -u

cd "`dirname $0`"

. settings.bash

echo "Installing schemata..."
cd schema/
install -m664 asterisk.schema "$UNI_SCHEMA_PATH/"
install -m664 asterisk4ucs.schema "$UNI_SCHEMA_PATH/"
install -m664 80asterisk "$UNI_TEMPLATE_PATH/files/etc/ldap/slapd.conf.d/"
install -m664 asterisk.info "$UNI_TEMPLATE_PATH/info/"
cd ..
echo -e "\t\t\t\t\t\t\tdone."

echo "Updating slapd.conf..."
univention-config-registry commit /etc/ldap/slapd.conf
echo -e "\t\t\t\t\t\t\tdone."

echo "Restarting slapd..."
invoke-rc.d slapd restart
if [ ! \( -r /var/run/slapd/slapd.pid \
	-a -d /proc/`cat /var/run/slapd/slapd.pid &>/dev/null`/ \) ]; then
	echo -e "\t\t\t\t\t\t\tfailed."
	echo "Slapd failed to start."
	echo "There is probably an error in one of the schema files."
	exit 1
fi
echo -e "\t\t\t\t\t\t\tdone."

echo "Installing icons..."
install -m664 icons/50x50/udm-asterisk* "$UNI_ICON_PATH/50x50/"
install -m664 icons/16x16/udm-asterisk* "$UNI_ICON_PATH/16x16/"
install -m664 icons/scalable/udm-asterisk* "$UNI_ICON_PATH/scalable/"
echo -e "\t\t\t\t\t\t\tdone."

echo "Installing UDM module..."
# syntax
mkdir -p "$UNI_UDM_PATH/syntax.d" "$UNI_UDM_LN_PATH/syntax.d"
install -m664 frontend/syntax/asterisk.py "$UNI_UDM_PATH/syntax.d/"
ln -fs "$UNI_UDM_PATH/syntax.d/asterisk.py" "$UNI_UDM_LN_PATH/syntax.d/"
# hook
mkdir -p "$UNI_UDM_PATH/hooks.d" "$UNI_UDM_LN_PATH/hooks.d"
install -m664 frontend/hooks/asterisk.py "$UNI_UDM_PATH/hooks.d/"
ln -fs "$UNI_UDM_PATH/hooks.d/asterisk.py" "$UNI_UDM_LN_PATH/hooks.d/"
# module
mkdir -p "$UNI_UDM_PATH/handlers/asterisk" "$UNI_UDM_LN_PATH/handlers/asterisk"
install -m664 frontend/asterisk/* "$UNI_UDM_PATH/handlers/asterisk/"
ln -fs "$UNI_UDM_PATH"/handlers/asterisk/* "$UNI_UDM_LN_PATH/handlers/asterisk/"
echo -e "\t\t\t\t\t\t\tdone."

echo "Creating extended attributes for UDM user module..."
frontend/user-phone-extension/install
echo -e "\t\t\t\t\t\t\tdone."

echo "Creating default container for asterisk data..."
frontend/default-container/install
echo -e "\t\t\t\t\t\t\tdone."

echo "Adding module Asterisk to UMC's main menu..."
# first try to reverse-apply the patch, in case it was applied already
# that may fail.
patch -ufsRr- "$UNI_UMC_PATH/modules/udm.xml" \
		frontend/wizard.patch &>/dev/null || true
# then apply the patch. this must not fail.
patch -ufsr- "$UNI_UMC_PATH/modules/udm.xml" frontend/wizard.patch
echo -e "\t\t\t\t\t\t\tdone."

echo "Restarting services..."
/etc/init.d/univention-management-console-web-server stop
/etc/init.d/univention-management-console-server stop
/etc/init.d/univention-management-console-server start
/etc/init.d/univention-management-console-web-server start
echo -e "\t\t\t\t\t\t\tdone."

echo "Installation successful."

