#!/bin/bash

set -e
set -u

cd "`dirname $0`"

. settings.sh

echo "Creating folder for autogenerated asterisk configuration files..."
mkdir -p "$ast4ucs_ucr_confpath"
echo -e "\t\t\t\t\t\t\tdone."

echo "Installing info-texts for UCR variables..."
install -m664 ucr/category.cfg \
			"$UNI_REGINFO_PATH/categories/asterisk_member.cfg"
install -m664 ucr/variables.cfg \
			"$UNI_REGINFO_PATH/variables/asterisk_member.cfg"
echo -e "\t\t\t\t\t\t\tdone."

echo "Setting default values for UCR variables..."
ucr set asterisk/confpath="$ast4ucs_ucr_confpath"
ucr set asterisk/asteriskbin="$ast4ucs_ucr_asteriskbin"
echo -e "\t\t\t\t\t\t\tdone."

echo "Installing directory listener module..."
install -m664 listener/asterisk.py "$UNI_LISTENER_PATH/asterisk.py"
echo -e "\t\t\t\t\t\t\tdone."

echo "Restarting univention directory listener..."
invoke-rc.d univention-directory-listener restart
echo -e "\t\t\t\t\t\t\tdone."

echo "Installation successful."

