#!/bin/bash

set -e
set -u

cd "`dirname $0`"

. settings.sh

echo "Deleting directory listener module..."
rm "$UNI_LISTENER_PATH/asterisk.py"
echo -e "\t\t\t\t\t\t\tdone."

echo "Restarting univention directory listener..."
invoke-rc.d univention-directory-listener restart
echo -e "\t\t\t\t\t\t\tdone."

echo "Deleting folder for autogenerated asterisk configuration files..."
rm -r "$ast4ucs_ucr_confpath"
echo -e "\t\t\t\t\t\t\tdone."

echo "Removing info-texts for UCR variables..."
rm "$UNI_REGINFO_PATH/categories/asterisk_member.cfg"
rm "$UNI_REGINFO_PATH/variables/asterisk_member.cfg"
echo -e "\t\t\t\t\t\t\tdone."

echo "Removing UCR variables..."
ucr unset asterisk/confpath
ucr unset asterisk/asteriskbin
echo -e "\t\t\t\t\t\t\tdone."

echo "Uninstallation successful."

