#!/bin/bash

# Copyright (C) 2012 DECOIT GmbH <asterisk4ucs@decoit.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e
set -u

cd "`dirname "$0"`"

UNI_UMC_PATH=/usr/share/univention-management-console

echo "Adding module Asterisk to UMC's main menu..."
# first try to reverse-apply the patch, in case it was applied already.
# that may fail.
patch -ufsRr- "$UNI_UMC_PATH/modules/udm.xml" wizard.patch &>/dev/null || true
# then apply the patch. this must not fail.
patch -ufsr- "$UNI_UMC_PATH/modules/udm.xml" wizard.patch
echo -e "\t\t\t\t\t\t\tdone."

