#!/bin/sh

case "$1" in
remove)
                test -e /etc/ldap/slapd.conf \
			&& /usr/sbin/univention-config-registry commit \
				/etc/ldap/slapd.conf
                test -x /etc/init.d/slapd && invoke-rc.d slapd restart
        ;;

purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

*)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0

