#!/bin/bash

# Copyright (C) 2012 DECOIT GmbH <asterisk4ucs@decoit.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e
set -u

eval "$(ucr shell)"

for name in ast4ucsPhoneSyntax ast4ucsMailboxSyntax; do
	udm settings/syntax remove \
		--dn "cn=$name,cn=univention,$ldap_base"
done

for name in phones mailbox extmode ringdelay timeout forwarding; do
	udm settings/extended_attribute remove \
		--dn "cn=$name,cn=custom attributes,cn=univention,$ldap_base"
done

